# Generated by Django 6.0.4 on 2026-04-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_order_product_poductimage_orderitem_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_acrive',
            new_name='is_active',
        ),
    ]
