# Generated by Django 6.0.4 on 2026-04-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_is_acrive_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poductimage',
            old_name='images',
            new_name='image',
        ),
    ]
