# Generated by Django 6.0.4 on 2026-04-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_images_poductimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoductImage',
            new_name='ProductImage',
        ),
    ]
